### ISSUE TITLE
Question regarding the start page

### ISSUE THREAD

**Issue by Ein-Tim** [MrWillCom/github-dark-mode#6]
Hey, I just installed this Extension from the Edge App Store and it works really well! Thanks for this great tool!

I just wanted to ask if it's normal that the main page (github.com) looks like this:

![image](https://user-images.githubusercontent.com/67682506/100142397-19557300-2e94-11eb-884a-912b6612d9a3.png)

It's a bit to "bright", isn't it? 😅

Thanks again! 
Best wishes 
Tim

**Comment by MrWillCom** [comment]
Hello, thanks for your feedback!

I think it's okay in my browser:

![A screenshot of the main page in my browser](https://user-images.githubusercontent.com/47271684/100452842-e52cbd00-30f4-11eb-819d-be3e77ce981b.jpeg)

You can try to update to the latest version to solve this problem.

Also, you can go to the details settings page of the extension to check the version:

![A screenshot of the details settings page of the extension](https://user-images.githubusercontent.com/47271684/100453226-95022a80-30f5-11eb-8af5-7ae0502f4964.jpeg)

The latest version is 0.2.2 .

Thanks! 😃

**Comment by Ein-Tim** [comment]
Okay, thanks... In the [Microsoft Edge-Add-Ons Store](https://microsoftedge.microsoft.com/addons/detail/github-dark-mode/mkmlkegjpmlpmdddbibkainphcilpagm) the latest version I can see is 0.2.1... How can I update to 0.2.2? 😀😅

![image](https://user-images.githubusercontent.com/67682506/100453990-4b491e00-30bc-11eb-8584-ec8ff283e369.png)

**Comment by MrWillCom** [comment]
Alright, it's my problem... I forgot to publish this version to Microsoft Edge Add-ons Store...

It's published and in review now.

![A screenshot of Microsoft Edge Add-ons dashboard](https://user-images.githubusercontent.com/47271684/100539484-dae3fd80-3271-11eb-988f-a156d6a9c041.png)

**Comment by Ein-Tim** [comment]
Okay thanks 👍
I will report back when I updated to 0.2.2

**Comment by Ein-Tim** [comment]
Updated to 0.2.2 and can confirm that it now looks right 👍
